DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employee;

CREATE TABLE department (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
dept_name VARCHAR(30) NOT NULL,
dept_id INTEGER NOT NULL
);

CREATE TABLE roles (
id INTEGER AUTO_INCREMENT PRIMARY KEY,  
job_title VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
role_dept VARCHAR(30) NOT NULL,
role_salary DECIMAL(7, 0) NOT NULL
);

CREATE TABLE employee (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
manager_id INTEGER
);